version: '3.8'

services:
  bytebot-desktop:
    # Build from source
    build:
      context: ../packages/
      dockerfile: bytebotd/Dockerfile
      cache_from:
        - type=local,src=../.docker-cache/bytebot-desktop
      cache_to:
        - type=local,dest=../.docker-cache/bytebot-desktop,mode=max
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot-desktop:edge
    shm_size: "2g"
    container_name: bytebot-desktop
    restart: unless-stopped
    hostname: computer
    privileged: true
    ports:
      - "9990:9990" # bytebotd service & noVNC exposed to host
    environment:
      - DISPLAY=:0
      - SCREENSHOT_COMPRESSION_ENABLED=${SCREENSHOT_COMPRESSION_ENABLED:-true}
      - SCREENSHOT_TARGET_SIZE_KB=${SCREENSHOT_TARGET_SIZE_KB:-512}
      - SCREENSHOT_INITIAL_QUALITY=${SCREENSHOT_INITIAL_QUALITY:-85}
      - SCREENSHOT_MIN_QUALITY=${SCREENSHOT_MIN_QUALITY:-40}
      - SCREENSHOT_MAX_WIDTH=${SCREENSHOT_MAX_WIDTH:-1280}
      - SCREENSHOT_MAX_HEIGHT=${SCREENSHOT_MAX_HEIGHT:-960}
      - SCREENSHOT_IMAGE_FORMAT=${SCREENSHOT_IMAGE_FORMAT:-jpeg}
      - MOUSE_AUTO_DELAY_MS=${MOUSE_AUTO_DELAY_MS:-300}
      - KEYBOARD_AUTO_DELAY_MS=${KEYBOARD_AUTO_DELAY_MS:-100}
    networks:
      - bytebot-network
    volumes:
      - bytebot_desktop_node_modules:/bytebot/bytebotd/node_modules
      - bytebot_npm_cache:/root/.npm
      - bytebot_node_gyp_cache:/root/.cache/node-gyp

  postgres:
    image: postgres:16-alpine
    container_name: bytebot-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bytebotdb
    networks:
      - bytebot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bytebot-agent:
    build:
      context: ../packages/
      dockerfile: bytebot-agent/Dockerfile
      cache_from:
        - type=local,src=../.docker-cache/bytebot-agent
      cache_to:
        - type=local,dest=../.docker-cache/bytebot-agent,mode=max
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot-agent:edge
    container_name: bytebot-agent
    restart: unless-stopped
    ports:
      - "9991:9991"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/bytebotdb}
      - BYTEBOT_DESKTOP_BASE_URL=${BYTEBOT_DESKTOP_BASE_URL:-http://bytebot-desktop:9990}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
    depends_on:
      - postgres
    networks:
      - bytebot-network
    volumes:
      - bytebot_agent_node_modules:/app/bytebot-agent/node_modules
      - bytebot_npm_cache:/root/.npm
      - bytebot_node_gyp_cache:/root/.cache/node-gyp

  bytebot-ui:
    build:
      context: ../packages/
      dockerfile: bytebot-ui/Dockerfile
      cache_from:
        - type=local,src=../.docker-cache/bytebot-ui
      cache_to:
        - type=local,dest=../.docker-cache/bytebot-ui,mode=max
      args:
        - BYTEBOT_AGENT_BASE_URL=${BYTEBOT_AGENT_BASE_URL:-http://bytebot-agent:9991}
        - BYTEBOT_DESKTOP_VNC_URL=${BYTEBOT_DESKTOP_VNC_URL:-http://bytebot-desktop:9990/websockify}
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot-ui:edge
    container_name: bytebot-ui
    restart: unless-stopped
    ports:
      - "9992:9992"
    environment:
      - NODE_ENV=production
      - BYTEBOT_AGENT_BASE_URL=${BYTEBOT_AGENT_BASE_URL:-http://bytebot-agent:9991}
      - BYTEBOT_DESKTOP_VNC_URL=${BYTEBOT_DESKTOP_VNC_URL:-http://bytebot-desktop:9990/websockify}
    depends_on:
      - bytebot-agent
    networks:
      - bytebot-network
    volumes:
      - bytebot_ui_node_modules:/app/bytebot-ui/node_modules
      - bytebot_ui_next_cache:/app/bytebot-ui/.next
      - bytebot_npm_cache:/root/.npm
      - bytebot_shared_node_modules:/app/shared/node_modules
      - bytebot_node_gyp_cache:/root/.cache/node-gyp

networks:
  bytebot-network:
    driver: bridge

volumes:
  postgres_data:
  bytebot_desktop_node_modules:
  bytebot_agent_node_modules:
  bytebot_ui_node_modules:
  bytebot_ui_next_cache:
  bytebot_npm_cache:
  bytebot_node_gyp_cache:
  bytebot_shared_node_modules:
